---
- name: Download containerd tarball
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz
    dest: /tmp/containerd-1.7.14-linux-amd64.tar.gz

- name: Install containerd binary
  command: tar Cxzvf /usr/local /tmp/containerd-1.7.14-linux-amd64.tar.gz

- name: Ensure the target directory exists
  file:
    path: /usr/lib/systemd/system
    state: directory
    mode: "0755"

- name: Download and install containerd service file
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /usr/lib/systemd/system/containerd.service

- name: Create containerd configuration directory
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate containerd configuration file
  ansible.builtin.shell: containerd config default | tee /etc/containerd/config.toml

- name: Enable systemd Cgroup in containerd config
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "^SystemdCgroup = false"
    line: "SystemdCgroup = true"

- name: Reload systemd and enable containerd service
  command: systemctl daemon-reload

- name: Start and enable containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: Download and install runc binary
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
    dest: /tmp/runc.amd64

- name: Install runc binary
  command: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

- name: Download and install CNI plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-amd64-v1.5.0.tgz
    dest: /tmp/cni-plugins-linux-amd64-v1.5.0.tgz

- name: Create /opt/cni/bin configuration directory
  file:
    path: /opt/cni/bin
    state: directory

- name: Extract CNI plugins
  ansible.builtin.shell: tar Cxzvf /opt/cni/bin /tmp/cni-plugins-linux-amd64-v1.5.0.tgz
