---
- name: Disable swap to meet Kubernetes requirements
  command: swapoff -a

- name: Load required kernel modules for Kubernetes
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Enable br_netfilter and overlay kernel modules
  command: modprobe "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl settings for Kubernetes networking
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Apply sysctl settings immediately
  command: sysctl --system

- name: Verify br_netfilter and overlay modules are loaded
  ansible.builtin.shell: lsmod | grep "{{ item }}"
  loop:
    - br_netfilter
    - overlay
  register: output-1

- name: Verify sysctl settings for Kubernetes
  command: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
  register: output-2

- name: Debug output for lsmod and sysctl
  debug:
    msg: >
      "lmsode {br_netfilter, overlay}: {{output-1}}"
      "sysctl settings : {{output-2}}"
