---
- name: Setup Kubernetes Cluster with containerd
  hosts: all
  become: yes
  roles:
    - base_system
    - containerd
    - kubernetes
# - name: Initialize Kubernetes Master Node
#   hosts: master
#   become: yes
#   roles:
#     - kubernetes_master

# - name: Join Kubernetes Worker Nodes
#   hosts: worker
#   become: yes
#   roles:
#     - kubernetes_worker
